// This file is generated by Firebase Studio.
'use server';

/**
 * @fileOverview This file defines the Genkit flow for generating story snippets based on user choices and a selected theme.
 *
 * The flow takes the theme, previous story snippets, and the user's current choice as input.
 * It uses an LLM to generate the next story snippet, ensuring the story adapts to user decisions and maintains narrative consistency.
 *
 * @exports generateStorySnippet - The main function to generate a story snippet.
 * @exports GenerateStorySnippetInput - The input type for the generateStorySnippet function.
 * @exports GenerateStorySnippetOutput - The output type for the generateStorySnippet function.
 */

import {ai} from '@/ai/ai-instance';
import {z} from 'genkit';

const GenerateStorySnippetInputSchema = z.object({
  theme: z.string().describe('The theme of the story (e.g., space, fantasy, horror).'),
  previousSnippets: z.array(z.string()).describe('An array of previous story snippets.'),
  currentChoice: z.string().describe('The user\'s current choice that influences the story.'),
});
export type GenerateStorySnippetInput = z.infer<typeof GenerateStorySnippetInputSchema>;

const GenerateStorySnippetOutputSchema = z.object({
  nextSnippet: z.string().describe('The next story snippet generated by the LLM.'),
});
export type GenerateStorySnippetOutput = z.infer<typeof GenerateStorySnippetOutputSchema>;

export async function generateStorySnippet(input: GenerateStorySnippetInput): Promise<GenerateStorySnippetOutput> {
  return generateStorySnippetFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateStorySnippetPrompt',
  input: {
    schema: z.object({
      theme: z.string().describe('The theme of the story.'),
      previousSnippets: z.array(z.string()).describe('Previous story snippets.'),
      currentChoice: z.string().describe('The user\'s current choice.'),
    }),
  },
  output: {
    schema: z.object({
      nextSnippet: z.string().describe('The next story snippet.'),
    }),
  },
  prompt: `You are an AI Dungeon Master, weaving a choose-your-own-adventure story.

The theme of the story is: {{{theme}}}

Previous story snippets:
{{#each previousSnippets}}
{{{this}}}
{{/each}}

The user has chosen: {{{currentChoice}}}

Generate the next story snippet, continuing the narrative based on the user's choice. The story should be engaging, creative, and consistent with the theme. The snippet should be no more than 200 words.

Next story snippet:`,
});

const generateStorySnippetFlow = ai.defineFlow<
  typeof GenerateStorySnippetInputSchema,
  typeof GenerateStorySnippetOutputSchema
>(
  {
    name: 'generateStorySnippetFlow',
    inputSchema: GenerateStorySnippetInputSchema,
    outputSchema: GenerateStorySnippetOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
